[build-system]
requires = [
    "setuptools>=61",
    "setuptools_scm[toml]>=3.4",
    "toml",
    "wheel"
]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/udar/version.py"
