OC_conflicts = {
                # OC_tag: set of conflicting udar tags
                'ADJF': {'N'},
                'ADJS': {'N'},
                'ADVB': {'A', 'CS', 'Pcle'},
                'CONJ': {'Pron', 'N', 'Interj', 'Adv'},
                'NOUN': {'A', 'Pr'},
                'NPRO': {'N', 'Pred', 'Pcle', 'Det'},
                'PREP': {'Interj', 'N', 'V'},
                'VERB': {'A', 'Pred'},
                'masc': {'Neu', 'Fem'},
                'femn': {'Msc'},
                'neut': {'Msc'},
                'sing': {'Pl'},
                'plur': {'Sg'},
                'nomn': {'Acc', 'Gen', 'Loc', 'Dat', 'Ins', 'Voc'},
                'gent': {'Nom', 'Acc', 'Loc', 'Dat', 'Ins', 'Voc'},
                'datv': {'Nom', 'Acc', 'Gen', 'Loc', 'Ins', 'Voc'},
                'accs': {'Nom', 'Gen', 'Loc', 'Dat', 'Ins', 'Voc'},
                'ablt': {'Nom', 'Acc', 'Gen', 'Loc', 'Dat', 'Voc'},
                'loct': {'Nom', 'Acc', 'Gen', 'Dat', 'Ins', 'Voc'},
                'voct': {'Nom', 'Acc', 'Gen', 'Loc', 'Dat', 'Ins'},
                'gen1': {'Nom', 'Acc', 'Loc', 'Dat', 'Ins', 'Voc'},
                'gen2': {'Nom', 'Acc', 'Loc', 'Dat', 'Ins', 'Voc'},
                'acc2': {'Nom', 'Gen', 'Loc', 'Dat', 'Ins', 'Voc'},
                'loc1': {'Nom', 'Acc', 'Gen', 'Dat', 'Ins', 'Voc'},
                'loc2': {'Nom', 'Acc', 'Gen', 'Dat', 'Ins', 'Voc'},
                'tran': {'IV'},
                'intr': {'TV'},
                }
